# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.

environment          = "development"
region               = "me-central-1"
az_count             = 2
db_instance_class    = "db.t4g.micro"
db_multi_az          = false
db_allocated_storage = 20
