# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
# ElastiCache Redis in the private tier, encrypted in transit and at rest.

resource "aws_elasticache_subnet_group" "this" {
  name       = "${var.name}-cache"
  subnet_ids = var.subnet_ids
}

resource "aws_security_group" "cache" {
  name        = "${var.name}-cache"
  description = "Redis access from application workloads only"
  vpc_id      = var.vpc_id

  ingress {
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = var.allowed_security_group_ids
    description     = "Redis from application workloads"
  }

  # No egress rule at all, deliberately.
  #
  # Security groups are stateful: replies to the queries the application sends are already
  # allowed by the ingress rule above. A managed cache never opens a connection of its own,
  # so "any protocol to anywhere" granted reach it has no use for — and gave anything that
  # did reach it a way out.

  tags = { Name = "${var.name}-cache" }
}

resource "aws_elasticache_replication_group" "this" {
  # At most 40 characters, a letter first, no double hyphen. A name that met that keeps it, so no
  # group is renamed; any other is cut and ends in a hash of the whole name, so environments and
  # projects that begin alike stay apart. Cut alone, staging and production shared one id
  # (REVIEW-36FA103 finding 5; Codex REVIEW-3972710 finding 3).
  replication_group_id = can(regex("^[a-z][a-z0-9]*(-[a-z0-9]+)*$", var.name)) && length(var.name) <= 34 ? "${var.name}-cache" : "${replace(substr(replace("${can(regex("^[a-z]", var.name)) ? "" : "app-"}${var.name}", "/-+/", "-"), 0, 25), "/-+$/", "")}-${substr(sha1(var.name), 0, 8)}-cache"
  description          = "Redis for ${var.name}"

  # The repository runs redis:7-alpine; the managed engine is kept on the same line.
  engine             = "redis"
  engine_version     = "7.1"
  node_type          = var.node_type
  num_cache_clusters = var.replicas

  # A single node cannot fail over; more than one can.
  automatic_failover_enabled = var.replicas > 1
  multi_az_enabled           = var.replicas > 1

  subnet_group_name  = aws_elasticache_subnet_group.this.name
  security_group_ids = [aws_security_group.cache.id]

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true

  maintenance_window       = "sun:05:00-sun:06:00"
  snapshot_retention_limit = 1

  tags = { Name = "${var.name}-cache" }
}
