# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
output "endpoint" {
  value = aws_elasticache_replication_group.this.primary_endpoint_address
}

output "security_group_id" {
  value = aws_security_group.cache.id
}
