# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
# Backend bootstrap.
#
# A separate root module that uses LOCAL state on purpose: it creates the bucket the main
# configuration stores its state in, and that bucket cannot store its own creation.
#
#     terraform init && terraform apply
#     # then copy state_bucket_name into ../backend.hcl
#
# Run once, ever. Its own state describes a single bucket, so losing it is a short
# `terraform import`, not an incident.

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.80"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project   = var.project_name
      ManagedBy = "Terraform"
      Purpose   = "terraform-remote-state"
    }
  }
}

data "aws_caller_identity" "current" {}

locals {
  # Globally unique without being unguessable: account id and region are the two things that
  # make a name unique to you and stable across re-runs.
  bucket_name = "${var.project_name}-tfstate-${data.aws_caller_identity.current.account_id}-${var.aws_region}"
}

resource "aws_s3_bucket" "state" {
  bucket = local.bucket_name

  # State is not reproducible. Refuse to destroy it by accident.
  lifecycle {
    prevent_destroy = true
  }
}

# Every apply overwrites the state object. Versioning is what makes a bad apply recoverable.
resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id

  versioning_configuration {
    status = "Enabled"
  }
}

# State holds database passwords and private keys in plaintext, so it gets a key of its own
# rather than the account-wide S3 default. A customer-managed key is what makes access
# auditable in CloudTrail and revocable independently of the bucket policy.
resource "aws_kms_key" "state" {
  description             = "Encrypts the ${var.project_name} Terraform state"
  deletion_window_in_days = 30
  enable_key_rotation     = true
}

resource "aws_kms_alias" "state" {
  name          = "alias/${var.project_name}-tfstate"
  target_key_id = aws_kms_key.state.key_id
}

resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.state.arn
      sse_algorithm     = "aws:kms"
    }
    # One data key per bucket rather than per object. Terraform reads state on every plan, so
    # this is the difference between a handful of KMS calls a day and thousands.
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket = aws_s3_bucket.state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Old versions accumulate on every apply. Keep enough to recover, not forever.
resource "aws_s3_bucket_lifecycle_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    id     = "expire-old-state-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }
}

# --- The pipeline's identities -------------------------------------------------------------
#
# The generated workflows assume three roles through GitHub's OIDC provider: no long-lived AWS
# key is stored in the repository. Nothing created them, so the pipeline could not run from what
# was delivered. Created when github_repository is set ("owner/name").
#
# - plan: a push to main or a pull request of that repository; reads the account and the state.
# - publish: a push to main; pushes this project's images to its ECR repositories and nothing
#   else. An image in a registry changes nothing that runs, so it needs no approval.
# - deploy: only a job in the repository's "production" environment, which the workflows use for
#   applying and rolling out, and on which a required reviewer is the approval. It cannot change
#   the pipeline's own roles.
#
# The deploy role is broad: it applies a whole stack (network, database, cache, containers, load
# balancer, roles for the tasks). The roles, policies and instance profiles it may manage are
# those under this project's IAM path, /pilot/<project>/ -- a path, not a name prefix, so
# project "shop" cannot reach project "shop-admin" -- and every role it creates carries the
# workload boundary. Narrow it further to your stack before relying on it for production.

locals {
  pipeline = var.github_repository != "" ? 1 : 0
  oidc_url = "token.actions.githubusercontent.com"
  # An account holds one provider for this URL. One already there (another project's) is reused
  # by its ARN, and never managed or destroyed from here.
  provider_arn = var.github_oidc_provider_arn != "" ? var.github_oidc_provider_arn : try(aws_iam_openid_connect_provider.github[0].arn, "")
  # What GitHub puts before ":ref:...", ":pull_request" or ":environment:..." in the token's
  # subject. Repositories using immutable subjects carry their IDs there
  # ("repo:owner@123/name@456"), and a trust naming "repo:owner/name" refuses every token
  # (G0, 2026-10-02). Read it from GitHub: GET /repos/OWNER/NAME/actions/oidc/customization/sub,
  # the sub_claim_prefix field.
  subject = var.github_oidc_subject_prefix != "" ? var.github_oidc_subject_prefix : "repo:${var.github_repository}"
}

resource "aws_iam_openid_connect_provider" "github" {
  count           = var.github_repository != "" && var.github_oidc_provider_arn == "" ? 1 : 0
  url             = "https://${local.oidc_url}"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = ["6938fd4d98bab03faadb97b34396831e3780aea1"]
}

data "aws_iam_policy_document" "plan_trust" {
  count = local.pipeline
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    principals {
      type        = "Federated"
      identifiers = [local.provider_arn]
    }
    condition {
      test     = "StringEquals"
      variable = "${local.oidc_url}:aud"
      values   = ["sts.amazonaws.com"]
    }
    # The two places the generated workflows plan from: a push to main (CD) and a pull request
    # (infrastructure.yml). Not `repo:<repo>:*`, which also admitted every other branch, tag and
    # environment of the repository.
    condition {
      test     = "StringEquals"
      variable = "${local.oidc_url}:sub"
      values = [
        "${local.subject}:ref:refs/heads/main",
        "${local.subject}:pull_request",
      ]
    }
  }
}

data "aws_iam_policy_document" "deploy_trust" {
  count = local.pipeline
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    principals {
      type        = "Federated"
      identifiers = [local.provider_arn]
    }
    condition {
      test     = "StringEquals"
      variable = "${local.oidc_url}:aud"
      values   = ["sts.amazonaws.com"]
    }
    condition {
      test     = "StringEquals"
      variable = "${local.oidc_url}:sub"
      values   = ["${local.subject}:environment:production"]
    }
  }
}

# The boundary on every role the stack creates. Created whether or not a pipeline is: the stack
# names it on its roles either way. Everything a workload may do, except write identities or
# change the organisation or the account -- so a role the deploy role writes cannot grant more
# than that, whatever its own policies say. Service-linked roles (EKS creates one for its load
# balancers) and IAM reads stay allowed.
data "aws_iam_policy_document" "workload_boundary" {
  # Anything outside IAM, the organisation and the account settings...
  statement {
    not_actions = ["iam:*", "organizations:*", "account:*"]
    resources   = ["*"]
  }
  # ...and in IAM only reads, and the service-linked roles AWS services create for themselves (EKS
  # does, for its load balancers). An allow-list: an IAM write not named here is outside it.
  statement {
    actions   = ["iam:Get*", "iam:List*", "iam:CreateServiceLinkedRole"]
    resources = ["*"]
  }
}

resource "aws_iam_policy" "workload_boundary" {
  name        = "${var.project_name}-workload-boundary"
  path        = "/pilot/${var.project_name}/"
  description = "Permissions boundary on every role the ${var.project_name} stack creates."
  policy      = data.aws_iam_policy_document.workload_boundary.json
}

data "aws_iam_policy_document" "publish_trust" {
  count = local.pipeline
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    principals {
      type        = "Federated"
      identifiers = [local.provider_arn]
    }
    condition {
      test     = "StringEquals"
      variable = "${local.oidc_url}:aud"
      values   = ["sts.amazonaws.com"]
    }
    condition {
      test     = "StringEquals"
      variable = "${local.oidc_url}:sub"
      values   = ["${local.subject}:ref:refs/heads/main"]
    }
  }
}

resource "aws_iam_role" "publish" {
  count              = local.pipeline
  name               = "${var.project_name}-pipeline-publish"
  path               = "/pilot/${var.project_name}/pipeline/"
  assume_role_policy = data.aws_iam_policy_document.publish_trust[0].json
}

data "aws_iam_policy_document" "publish" {
  statement {
    actions   = ["ecr:GetAuthorizationToken"]
    resources = ["*"]
  }
  statement {
    actions = [
      "ecr:BatchCheckLayerAvailability", "ecr:InitiateLayerUpload", "ecr:UploadLayerPart",
      "ecr:CompleteLayerUpload", "ecr:PutImage", "ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer",
      "ecr:DescribeImages", "ecr:DescribeRepositories"
    ]
    resources = [for name in var.ecr_repositories : "arn:aws:ecr:${var.aws_region}:${data.aws_caller_identity.current.account_id}:repository/${name}"]
  }
}

resource "aws_iam_role_policy" "publish" {
  count  = local.pipeline
  role   = aws_iam_role.publish[0].id
  policy = data.aws_iam_policy_document.publish.json

  lifecycle {
    replace_triggered_by = [aws_iam_role.publish[0].unique_id]
  }
}

# Both read and write the state: a plan takes the state lock, which is an object in the bucket.
data "aws_iam_policy_document" "state" {
  statement {
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_bucket.state.arn]
  }
  statement {
    actions   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
    resources = ["${aws_s3_bucket.state.arn}/*"]
  }
  statement {
    actions   = ["kms:Decrypt", "kms:Encrypt", "kms:GenerateDataKey", "kms:DescribeKey"]
    resources = [aws_kms_key.state.arn]
  }
}

resource "aws_iam_role" "plan" {
  count              = local.pipeline
  name               = "${var.project_name}-pipeline-plan"
  path               = "/pilot/${var.project_name}/pipeline/"
  assume_role_policy = data.aws_iam_policy_document.plan_trust[0].json
}

resource "aws_iam_role_policy_attachment" "plan_read" {
  count      = local.pipeline
  role       = aws_iam_role.plan[0].name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"

  lifecycle {
    replace_triggered_by = [aws_iam_role.plan[0].unique_id]
  }
}

resource "aws_iam_role_policy" "plan_state" {
  count  = local.pipeline
  role   = aws_iam_role.plan[0].id
  policy = data.aws_iam_policy_document.state.json

  lifecycle {
    replace_triggered_by = [aws_iam_role.plan[0].unique_id]
  }
}

resource "aws_iam_role" "deploy" {
  count              = local.pipeline
  name               = "${var.project_name}-pipeline-deploy"
  path               = "/pilot/${var.project_name}/pipeline/"
  assume_role_policy = data.aws_iam_policy_document.deploy_trust[0].json
}

resource "aws_iam_role_policy_attachment" "deploy_power" {
  count      = local.pipeline
  role       = aws_iam_role.deploy[0].name
  policy_arn = "arn:aws:iam::aws:policy/PowerUserAccess"

  lifecycle {
    replace_triggered_by = [aws_iam_role.deploy[0].unique_id]
  }
}

data "aws_iam_policy_document" "deploy_iam" {
  statement {
    actions = ["iam:*Role*", "iam:*Policy*", "iam:*InstanceProfile*", "iam:TagRole", "iam:UntagRole"]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/pilot/${var.project_name}/*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/pilot/${var.project_name}/*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:instance-profile/pilot/${var.project_name}/*"
    ]
  }
  # A stack first applied before IAM paths has its roles at "/". Moving them to the path replaces
  # them, and the old ones must go: only those, carrying this project's Application tag -- which
  # the stack's provider puts on every resource -- and only to list, detach and delete. Not to
  # create, tag, change or pass one there: a tag on a role named like this project's could then
  # be written by this role, and a neighbour's or a hand-made role taken over.
  statement {
    actions = [
      "iam:GetRole", "iam:ListAttachedRolePolicies", "iam:ListRolePolicies", "iam:ListInstanceProfilesForRole",
      "iam:DetachRolePolicy", "iam:DeleteRolePolicy", "iam:DeleteRole", "iam:GetInstanceProfile",
      "iam:RemoveRoleFromInstanceProfile", "iam:DeleteInstanceProfile", "iam:ListPolicyVersions",
      "iam:DeletePolicyVersion", "iam:DeletePolicy"
    ]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${var.project_name}-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/${var.project_name}-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:instance-profile/${var.project_name}-*"
    ]
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/Application"
      values   = [var.project_name]
    }
    # And made by the stack: its provider tags everything it creates so, which a hand-made role
    # with the organisation's Application tag is not (REVIEW-1762C48 finding 2).
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/GeneratedBy"
      values   = ["EgyKode Pilot"]
    }
  }
  statement {
    actions   = ["iam:CreateServiceLinkedRole", "iam:GetRole", "iam:ListRoles", "iam:ListPolicies", "iam:GetPolicy", "iam:GetPolicyVersion"]
    resources = ["*"]
  }
  # An EKS cluster's own OIDC provider, which the cluster module creates. Only EKS's issuer in this
  # region: the account's GitHub provider is outside it.
  statement {
    actions = [
      "iam:CreateOpenIDConnectProvider", "iam:DeleteOpenIDConnectProvider", "iam:GetOpenIDConnectProvider",
      "iam:TagOpenIDConnectProvider", "iam:UntagOpenIDConnectProvider", "iam:UpdateOpenIDConnectProviderThumbprint",
      "iam:AddClientIDToOpenIDConnectProvider", "iam:RemoveClientIDFromOpenIDConnectProvider"
    ]
    resources = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/oidc.eks.${var.aws_region}.amazonaws.com/id/*"]
  }
  # The pipeline's own roles share the project prefix above. Without this the deploy role could
  # attach AdministratorAccess to itself or rewrite its own trust or the plan role's.
  statement {
    effect    = "Deny"
    actions   = ["iam:*"]
    resources = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/pilot/${var.project_name}/pipeline/*"]
  }
  # Every role it creates or gives permissions to carries the workload boundary, and keeps it;
  # the boundary itself is not its to change.
  statement {
    effect    = "Deny"
    actions   = ["iam:CreateRole", "iam:PutRolePermissionsBoundary", "iam:PutRolePolicy", "iam:AttachRolePolicy"]
    resources = ["*"]
    condition {
      test     = "StringNotEquals"
      variable = "iam:PermissionsBoundary"
      values   = [aws_iam_policy.workload_boundary.arn]
    }
  }
  statement {
    effect    = "Deny"
    actions   = ["iam:DeleteRolePermissionsBoundary"]
    resources = ["*"]
  }
  statement {
    effect    = "Deny"
    actions   = ["iam:CreatePolicyVersion", "iam:DeletePolicy", "iam:DeletePolicyVersion", "iam:SetDefaultPolicyVersion", "iam:TagPolicy", "iam:UntagPolicy"]
    resources = [aws_iam_policy.workload_boundary.arn]
  }
  # Nor may it attach an administrator-class managed policy to any role it manages.
  statement {
    effect    = "Deny"
    actions   = ["iam:AttachRolePolicy"]
    resources = ["*"]
    condition {
      test     = "ArnLike"
      variable = "iam:PolicyARN"
      values   = ["arn:aws:iam::aws:policy/AdministratorAccess", "arn:aws:iam::aws:policy/IAMFullAccess", "arn:aws:iam::aws:policy/PowerUserAccess"]
    }
  }
}

resource "aws_iam_role_policy" "deploy_iam" {
  count  = local.pipeline
  role   = aws_iam_role.deploy[0].id
  policy = data.aws_iam_policy_document.deploy_iam.json

  lifecycle {
    replace_triggered_by = [aws_iam_role.deploy[0].unique_id]
  }
}

resource "aws_iam_role_policy" "deploy_state" {
  count  = local.pipeline
  role   = aws_iam_role.deploy[0].id
  policy = data.aws_iam_policy_document.state.json

  lifecycle {
    replace_triggered_by = [aws_iam_role.deploy[0].unique_id]
  }
}
