# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
output "state_bucket_name" {
  description = "Put this in ../backend.hcl as the `bucket` value."
  value       = aws_s3_bucket.state.id
}

output "state_kms_key_arn" {
  description = "Put this in ../backend.hcl as the `kms_key_id` value."
  value       = aws_kms_key.state.arn
}

output "plan_role_arn" {
  description = "The repository secret AWS_PLAN_ROLE_ARN. Empty when github_repository is not set."
  value       = try(aws_iam_role.plan[0].arn, "")
}

output "workload_boundary_arn" {
  description = "The permissions boundary every role of the stack carries."
  value       = aws_iam_policy.workload_boundary.arn
}

output "publish_role_arn" {
  description = "The repository secret AWS_PUBLISH_ROLE_ARN. Empty when github_repository is not set."
  value       = try(aws_iam_role.publish[0].arn, "")
}

output "deploy_role_arn" {
  description = "The repository secret AWS_DEPLOY_ROLE_ARN. Empty when github_repository is not set."
  value       = try(aws_iam_role.deploy[0].arn, "")
}

output "init_command" {
  description = "Copy-paste to initialise the main configuration against this bucket."
  value       = "terraform init -backend-config=backend.hcl"
}
