# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
variable "project_name" {
  description = "Prefix for the state bucket name."
  type        = string
  default     = "repo"
}

variable "aws_region" {
  description = "Region the state bucket lives in."
  type        = string
  default     = "us-east-1"
}

variable "github_repository" {
  description = "The GitHub repository the workflows run in, as owner/name. Set, the pipeline's three roles are created; empty, none are."
  type        = string
  default     = ""

  validation {
    condition     = var.github_repository == "" || can(regex("^[A-Za-z0-9-]+/[A-Za-z0-9._-]+$", var.github_repository))
    error_message = "github_repository is owner/name, such as octo-org/orders."
  }
}

variable "ecr_repositories" {
  description = "The ECR repositories the publish role may push to: the stack's own (its repositories variable)."
  type        = list(string)
  default     = ["services-api-0df5335f3fb1e0cd", "services-worker-5b9b422f15d4c509"]
}

variable "github_oidc_subject_prefix" {
  description = "The repository's OIDC subject prefix, as GitHub reports it (GET /repos/OWNER/NAME/actions/oidc/customization/sub: sub_claim_prefix), e.g. repo:owner@123/name@456. Empty: repo:<github_repository>, which only repositories without immutable subjects use."
  type        = string
  default     = ""

  validation {
    condition     = var.github_oidc_subject_prefix == "" || can(regex("^repo:[^:]+$", var.github_oidc_subject_prefix))
    error_message = "github_oidc_subject_prefix is repo:<owner>/<name>, with the IDs GitHub adds where it uses them, and nothing after it."
  }

  # A prefix copied from another repository would trust that repository with all three roles.
  validation {
    condition     = var.github_oidc_subject_prefix == "" || lower(replace(var.github_oidc_subject_prefix, "/@[0-9]+/", "")) == lower("repo:${var.github_repository}")
    error_message = "github_oidc_subject_prefix names a different repository from github_repository."
  }
}

variable "github_oidc_provider_arn" {
  description = "An existing IAM OIDC provider for token.actions.githubusercontent.com to reuse; an account holds one. Empty: one is created."
  type        = string
  default     = ""
}
