# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
# Remote state in S3.
#
# The bucket name is deliberately not written here. S3 bucket names are globally unique across
# every AWS account, so a literal value in a tracked file breaks for the next person who clones
# this repository. Values come from backend.hcl, which is gitignored.
#
# The bucket must exist first. Create it once with ./bootstrap, then:
#
#     cd bootstrap && terraform init && terraform apply
#     cd ..        && terraform init -backend-config=backend.hcl

terraform {
  backend "s3" {
    # Backend blocks cannot use variables or interpolation — the backend is initialised
    # before variables are evaluated. Partial configuration is the supported way around it.

    # Encrypt the state object at rest.
    encrypt = true

    # Lock via a conditional write on an S3 object (`<key>.tflock`), which replaces the
    # separate DynamoDB table that older configurations used. Terraform 1.10+.
    use_lockfile = true
  }
}
