# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
# Root composition. Each concern is a module so environments differ only by tfvars.

data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  name = "${var.app_name}-${var.environment}"
  azs  = slice(data.aws_availability_zones.available.names, 0, var.az_count)

  # The identity the workloads actually run with, named once so every managed data store
  # trusts the same thing. On Kubernetes this is the group AWS attaches to managed node
  # ENIs; the custom control-plane group is not on the nodes and trusting it permits nothing.
  workload_security_group_id = module.service.task_security_group_id
}

# The workload boundary the bootstrap creates (terraform/bootstrap). Every role this stack
# creates carries it, under this project's IAM path; the pipeline's deploy role can create no
# role without it, and manages nothing outside the path. Looked up rather than named, so a
# bootstrap from before the boundary fails the plan -- before approval -- not the apply.
data "aws_caller_identity" "boundary" {}

data "aws_iam_policy" "boundary" {
  arn = "arn:aws:iam::${data.aws_caller_identity.boundary.account_id}:policy/pilot/${var.app_name}/${var.app_name}-workload-boundary"
}

locals {
  iam_path                 = var.iam_path != "" ? var.iam_path : "/pilot/${var.app_name}/"
  permissions_boundary_arn = data.aws_iam_policy.boundary.arn
}

module "network" {
  source = "./modules/network"

  name     = local.name
  vpc_cidr = var.vpc_cidr
  azs      = local.azs

  # These values come from the candidate that was selected and priced. Environment names do
  # not silently substitute a different network topology.
  egress_mode          = "gateway"
  nat_gateway_count    = 1
  enable_vpc_endpoints = false
}

module "ecr" {
  source = "./modules/ecr"

  repositories = var.repositories
}


module "database" {
  source = "./modules/database"

  name              = local.name
  subnet_ids        = module.network.private_subnet_ids
  vpc_id            = module.network.vpc_id
  instance_class    = var.db_instance_class
  multi_az          = var.db_multi_az
  allocated_storage = var.db_allocated_storage

  # The workloads' own security group. This list gates ingress and defaults to empty, so
  # omitting it provisions a database nothing can reach — running, billed, and unreachable.
  allowed_security_group_ids = [local.workload_security_group_id]

  # Never store a password in state or in the repository.
  manage_master_user_password = true

  backup_retention_period = coalesce(var.db_backup_retention_days, var.environment == "production" ? 7 : 1)
  deletion_protection     = var.environment == "production"
  final_snapshot          = var.environment == "production"
}


module "cache" {
  source = "./modules/cache"

  name       = local.name
  subnet_ids = module.network.private_subnet_ids
  vpc_id     = module.network.vpc_id
  node_type  = var.cache_node_type
  replicas   = 1

  # The same identity the database trusts: one runtime, one group.
  allowed_security_group_ids = [local.workload_security_group_id]
}

module "service" {
  source = "./modules/ecs"

  name                     = local.name
  permissions_boundary_arn = local.permissions_boundary_arn
  iam_path                 = local.iam_path
  vpc_id                   = module.network.vpc_id
  private_subnet_ids       = module.network.private_subnet_ids
  public_subnet_ids        = module.network.public_subnet_ids
  container_port           = 3000
  health_check_path        = "/health"
  health_check_matcher     = "200-399"
  cpu_architecture         = "X86_64"
  desired_count            = 3
  max_count                = 6
  task_cpu                 = 512
  task_memory              = 1024
  certificate_arn          = var.certificate_arn
  worker_enabled           = true
  worker_command           = []
  worker_desired_count     = 1
  worker_task_cpu          = 512
  worker_task_memory       = 1024
  environment = {
    DB_NAME      = "app"
    DB_HOST      = module.database.address
    DB_PORT      = "5432"
    DB_SSL_MODE  = "verify-full"
    DB_CA_BUNDLE = "/etc/ssl/certs/rds-global-bundle.pem"
    REDIS_URL    = "rediss://${module.cache.endpoint}:6379/0"
  }
  secrets = {
    DB_USER     = "${module.database.secret_arn}:username::"
    DB_PASSWORD = "${module.database.secret_arn}:password::"
  }
}

output "database_address" {
  description = "Read by the cluster stage, which declares the ConfigMap the workload reads."
  value       = module.database.address
}

output "database_port" {
  description = "Read by the cluster stage."
  value       = module.database.port
}

output "database_endpoint" {
  value     = module.database.endpoint
  sensitive = true
}

output "cache_address" {
  description = "Read by the runtime configuration stage; this value exists only after apply."
  value       = module.cache.endpoint
}

output "cache_port" {
  description = "TLS port exposed by the selected ElastiCache replication group."
  value       = 6379
}


output "load_balancer_dns" {
  value = module.service.load_balancer_dns
}

output "application_url" {
  description = <<-EOT
    The host delivery checks after a rollout.

    The load balancer name until a certificate and a domain front it, and the domain once they
    do -- a balancer DNS name is not covered by the certificate, so checking HTTPS against it
    would fail verification and checking HTTP would be answered by the redirect.
  EOT
  value       = var.application_host != "" ? var.application_host : module.service.load_balancer_dns
}


output "repository_urls" {
  value = module.ecr.repository_urls
}
