# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
variable "app_name" {
  description = "Application name, used as a prefix for every resource."
  type        = string
  default     = "repo"
}

variable "iam_path" {
  description = "The IAM path of this stack's roles, policies and instance profiles. Empty: /pilot/<app_name>/. A stack first applied before Pilot used paths keeps '/' -- moving it replaces every role, and an EKS cluster with its role."
  type        = string
  default     = ""
}

variable "environment" {
  description = "Deployment environment."
  type        = string
  validation {
    condition     = contains(["development", "staging", "production"], var.environment)
    error_message = "environment must be development, staging or production."
  }
}

variable "region" {
  description = "AWS region."
  type        = string
  default     = "me-central-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}

variable "application_host" {
  description = <<-EOT
    The hostname users reach, without a scheme or a path.

    A hostname, not a URL: the health check builds the scheme from whether a certificate is
    configured, and a value carrying one would produce https://https://host. Empty means the
    load balancer name, which is only checkable over plain HTTP.
  EOT
  type        = string
  default     = ""

  validation {
    condition     = !can(regex("://", var.application_host))
    error_message = "application_host is a hostname such as api.example.com, not a URL."
  }
}

variable "certificate_arn" {
  description = <<-EOT
    ACM certificate for the HTTPS listener.

    Empty means the load balancer serves plain HTTP, which is a preview configuration and not a
    production one. A certificate and a domain cannot be generated here, so this is the input
    that turns the ingress into a production one -- and generation says so until it is set.
  EOT
  type        = string
  default     = ""
}

variable "az_count" {
  description = "Number of availability zones to span."
  type        = number
  default     = 2
}

variable "db_instance_class" {
  description = "RDS instance class, sized by EgyKode Pilot from the declared traffic."
  type        = string
  default     = "db.t4g.small"
}

variable "db_multi_az" {
  description = "Synchronous standby in a second availability zone."
  type        = bool
  default     = false
}

# Unset, production keeps 7 days and every other environment one. An AWS account on the
# free plan accepts at most one day, and refused the production database outright; set it to 1
# there, knowing a restore can then reach back one day only.
variable "db_backup_retention_days" {
  description = "Days of automated database backups. Unset: 7 in production, 1 elsewhere."
  type        = number
  default     = null
}

variable "db_allocated_storage" {
  description = "Initial database storage in GB."
  type        = number
  default     = 50
}

variable "cache_node_type" {
  description = "ElastiCache node type."
  type        = string
  default     = "cache.t4g.micro"
}


variable "repositories" {
  description = "One ECR repository per independently deployable service."
  type        = list(string)
  default     = ["services-api-0df5335f3fb1e0cd", "services-worker-5b9b422f15d4c509"]
}
