# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
# The backend lives in backend.tf, not here.
#
# A module may declare only one `backend` block, and a second one fails `terraform init`
# before it reads anything else — so this file is providers and version constraints only.

terraform {
  # 1.10 is the floor: backend.tf locks state with a conditional write on the state object
  # (`use_lockfile`), which older versions do not understand.
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.80"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Application = var.app_name
      Environment = var.environment
      ManagedBy   = "terraform"
      GeneratedBy = "EgyKode Pilot"
    }
  }
}
