# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
variable "name" {
  description = "Name prefix for every resource in this module."
  type        = string
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
}

variable "azs" {
  description = "Availability zones to span."
  type        = list(string)
}

variable "egress_mode" {
  description = "Exact egress implementation selected by the architecture engine."
  type        = string

  validation {
    condition     = contains(["none", "gateway", "nat-instance"], var.egress_mode)
    error_message = "egress_mode must be none, gateway or nat-instance."
  }
}

variable "nat_gateway_count" {
  description = "Exact number of managed NAT gateways selected and priced."
  type        = number
  default     = 1

  validation {
    condition     = var.nat_gateway_count >= 1
    error_message = "nat_gateway_count must be at least one."
  }
}

variable "enable_vpc_endpoints" {
  description = "Provision the S3 and ECR endpoints included in the selected candidate."
  type        = bool
  default     = false
}

variable "nat_instance_type" {
  description = "Instance class priced by the NAT-instance candidate."
  type        = string
  default     = "t4g.small"
}
