# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
output "cluster_name" {
  value = aws_ecs_cluster.this.name
}

output "service_name" {
  value = aws_ecs_service.this.name
}

output "task_security_group_id" {
  value = aws_security_group.task.id
}

output "intended_desired_count" {
  description = "Tasks this service is sized for. Delivery scales to it; Terraform does not re-assert it."
  value       = var.desired_count
}

output "worker_service_name" {
  description = "Empty where this repository has no worker."
  value       = join("", aws_ecs_service.worker[*].name)
}

output "worker_task_family" {
  description = "Empty where this repository has no worker."
  value       = join("", aws_ecs_task_definition.worker[*].family)
}

output "intended_worker_count" {
  description = "Worker tasks this architecture is sized for, and the count delivery scales to."
  value       = var.worker_desired_count
}

output "load_balancer_dns" {
  value = aws_lb.this.dns_name
}
