# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
variable "name" {
  type = string
}

variable "permissions_boundary_arn" {
  type        = string
  default     = null
  description = "The permissions boundary every role here carries: the bootstrap's workload boundary. The deploy role creates no role without it."
}

variable "iam_path" {
  type        = string
  default     = "/"
  description = "The IAM path of every role, policy and instance profile here: /pilot/<project>/, the only path the pipeline's deploy role may manage."
}

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "vpc_id" {
  type = string
}

variable "private_subnet_ids" {
  type = list(string)
}

variable "public_subnet_ids" {
  type = list(string)
}

variable "container_port" {
  type = number
}

variable "health_check_path" {
  description = "Static HTTP health route. Use / with a broad matcher only when no route is proven."
  type        = string
}

variable "health_check_matcher" {
  description = "ALB success codes for the health route."
  type        = string
  default     = "200-399"
}

variable "cpu_architecture" {
  description = "Processor architecture of the image published by the generated pipeline."
  type        = string

  validation {
    condition     = contains(["X86_64", "ARM64"], var.cpu_architecture)
    error_message = "cpu_architecture must be X86_64 or ARM64."
  }
}

variable "image" {
  description = <<-EOT
    Placeholder the task definition is created with, never the application.

    The service has to exist before an image can be deployed to it, and the image is built by
    the pipeline that runs after this applies -- so the first apply has nothing real to point
    at. It creates the service with zero tasks (see initial_desired_count), so this image is
    never started and never answers a request. Delivery registers a revision holding the image
    it built and scales the service up.
  EOT
  type        = string
  default     = "public.ecr.aws/nginx/nginx:latest"
}

variable "initial_desired_count" {
  description = <<-EOT
    Tasks the service is created with. Zero, so no placeholder ever serves traffic.

    Only the initial value: desired_count is ignored after creation because delivery owns it,
    and Terraform re-asserting it would fight every deployment and every autoscaling decision.
  EOT
  type        = number
  default     = 0
}

variable "certificate_arn" {
  description = "ACM certificate for the HTTPS listener. Empty means the load balancer serves plain HTTP, which is not a production configuration."
  type        = string
  default     = ""
}

variable "environment" {
  description = "Non-secret values the workload reads, by variable name."
  type        = map(string)
  default     = {}
}

variable "secrets" {
  description = "Secrets Manager ARNs the workload reads, by variable name. May carry a JSON key."
  type        = map(string)
  default     = {}
}

variable "desired_count" {
  type = number
}

variable "max_count" {
  type = number
}

variable "task_cpu" {
  type = number
}

variable "task_memory" {
  type = number
}

variable "worker_enabled" {
  description = <<-EOT
    Whether this repository has a background workload to run.

    False creates none of the worker resources. Separate from the command below because a
    workload built from its own Dockerfile needs no command override -- that image's CMD is
    already what it runs.
  EOT
  type        = bool
  default     = false
}

variable "worker_command" {
  description = <<-EOT
    The command that overrides the image's own, where the worker shares the service's image.

    The command the repository declares -- a Procfile line, a package script -- not a guess from
    a queue library name. Empty means the image starts the right process on its own, which is
    the case when this workload has its own Dockerfile.
  EOT
  type        = list(string)
  default     = []
}

variable "worker_desired_count" {
  description = "Worker tasks this architecture is sized and priced for. Delivery scales to it."
  type        = number
  default     = 0
}

variable "worker_task_cpu" {
  type    = number
  default = 256
}

variable "worker_task_memory" {
  type    = number
  default = 512
}
