# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
variable "repositories" {
  description = "Repository names, one per service."
  type        = list(string)
  default     = ["services-api-0df5335f3fb1e0cd", "services-worker-5b9b422f15d4c509"]
}

variable "keep_images" {
  description = "How many tagged images to retain per repository."
  type        = number
  default     = 20
}
