# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
# Managed PostgreSQL in the private tier. Never publicly accessible.

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-db"
  subnet_ids = var.subnet_ids
  tags       = { Name = "${var.name}-db" }
}

resource "aws_security_group" "db" {
  name        = "${var.name}-db"
  description = "Database access from inside the VPC only"
  vpc_id      = var.vpc_id

  # Referencing a security group rather than a CIDR means only the workloads
  # that carry that group can reach the database.
  ingress {
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = var.allowed_security_group_ids
    description     = "PostgreSQL from application workloads"
  }

  # No egress rule at all, deliberately.
  #
  # Security groups are stateful: replies to the queries the application sends are already
  # allowed by the ingress rule above. A managed database never opens a connection of its own,
  # so "any protocol to anywhere" granted reach it has no use for — and gave anything that
  # did reach it a way out.

  tags = { Name = "${var.name}-db" }
}

# The final snapshot's name ends in the time this was first created: fixed then, so a later plan
# does not rename it, and a resource of its own, so a database created before it had a name gets
# one at the next apply. Kept on the database with ignore_changes instead, a missing name stayed
# missing through every apply, and the destroy's advice to apply first could not work
# (REVIEW-36FA103 finding 2). A new name is recorded in state; the database is not modified.
#
# A new time comes with every change that replaces the database: a replacement given the name of
# the snapshot its predecessor's delete took met that snapshot at its own delete (REVIEW-3972710
# finding 1). A database replaced by hand (-replace, or after a create that failed) keeps it.
resource "terraform_data" "final_snapshot_suffix" {
  input            = formatdate("YYYYMMDDhhmmss", timestamp())
  triggers_replace = ["postgres", var.name, var.database_name, var.master_username]

  lifecycle {
    ignore_changes = [input]
  }
}

# RDS names start with a letter and hold no double hyphen. A repository called 3d-viewer, or a
# name cut at 40 characters on a hyphen, gives var.name neither; only names AWS refused change.
resource "aws_db_instance" "this" {
  # The repository runs postgres:16-alpine; the managed engine is kept on the same line.
  identifier     = "${replace("${can(regex("^[a-z]", var.name)) ? "" : "app-"}${var.name}", "/-+/", "-")}-db"
  engine         = "postgres"
  engine_version = "16"
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.allocated_storage * 4
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.database_name
  username = var.master_username

  # Managed by AWS in Secrets Manager: the password never enters Terraform state.
  manage_master_user_password = var.manage_master_user_password

  multi_az               = var.multi_az
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false

  backup_retention_period = var.backup_retention_period
  backup_window           = "03:00-04:00"
  maintenance_window      = "sun:04:00-sun:05:00"
  copy_tags_to_snapshot   = true

  auto_minor_version_upgrade = true
  deletion_protection        = var.deletion_protection
  # The final snapshot has its own switch. Tied to the protection, turning the protection off
  # to destroy also dropped the snapshot; and a fixed name met the snapshot an earlier destroy
  # kept, which stopped the next destroy half-way (REVIEW-DC373BC finding 2). The name is set
  # whether or not a snapshot is wanted, so switching one on later has a name to use
  # (REVIEW-435B92F finding 3).
  skip_final_snapshot       = !var.final_snapshot
  final_snapshot_identifier = "${replace("${can(regex("^[a-z]", var.name)) ? "" : "app-"}${var.name}", "/-+/", "-")}-final-${terraform_data.final_snapshot_suffix.output}"

  performance_insights_enabled = true

  tags = { Name = "${var.name}-db" }
}
