# Generated by EgyKode Pilot (https://egykode.com) — review before merging.
# This file is a starting point, not a finished production configuration.
output "endpoint" {
  value     = aws_db_instance.this.endpoint
  sensitive = true
}

# The endpoint above is "host:port". The application needs the two separately, and splitting a
# string in the consumer puts text surgery between the database and the workload for two values
# the resource already exposes.
output "address" {
  description = "Hostname, without the port."
  value       = aws_db_instance.this.address
}

output "port" {
  value = aws_db_instance.this.port
}

output "security_group_id" {
  value = aws_security_group.db.id
}

output "secret_arn" {
  description = "Secrets Manager secret holding the master credentials."
  value       = try(aws_db_instance.this.master_user_secret[0].secret_arn, null)
}
